version: "3.9"
services:
  app:
    build: .
    environment:
      - API_KEY=${API_KEY:-devkey}
      - LLM_PROVIDER=${LLM_PROVIDER:-dummy}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_DEPLOYMENT=${AZURE_OPENAI_DEPLOYMENT:-}
      - EMBEDDINGS_PROVIDER=${EMBEDDINGS_PROVIDER:-hash}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      - INDEX_DIR=${INDEX_DIR:-data/index}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - CHUNK_SIZE=${CHUNK_SIZE:-800}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-120}
      - TOP_K=${TOP_K:-4}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - redis
      - prometheus
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_rules:/etc/prometheus/rules:ro
  grafana:
    image: grafana/grafana:10.1.5
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana_provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana_dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
