global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "genai_microservice"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: /metrics

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
